package com.voltaras.billservice.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Configures OpenAPI documentation and Swagger UI for the
 * VOLTARAS Bill Service.
 *
 * <p>
 * Swagger documentation is generated by bill-service on port 8084, while
 * API requests are executed through the API Gateway on port 8080.
 * </p>
 */
@Configuration
public class OpenApiConfig {

    private static final String SECURITY_SCHEME_NAME = "bearerAuth";

    @Bean
    public OpenAPI billServiceOpenAPI() {

        // Swagger executes protected API requests through API Gateway.
        Server gatewayServer = new Server()
                .url("http://localhost:8080")
                .description("VOLTARAS API Gateway");

        // Direct bill-service URL is useful only for local debugging.
        Server billServiceServer = new Server()
                .url("http://localhost:8084")
                .description("Bill Service - Direct Local Access");

        Contact contact = new Contact()
                .name("VOLTARAS Development Team");

        License license = new License()
                .name("VOLTARAS Project License");

        Info apiInfo = new Info()
                .title("VOLTARAS Bill Service API")
                .version("1.0.0")
                .description("""
                        REST API documentation for the VOLTARAS Bill Service.

                        This service manages:

                        • Electricity bill generation from verified meter readings
                        • Tariff-slab energy charge calculation
                        • Fixed charges, taxes, late fees, discounts and totals
                        • Consumer bill history, period filtering and outstanding bills
                        • Admin bill management (generate, update, cancel, payments)
                        • Marking overdue bills and applying late fees

                        Authentication is performed by the API Gateway using JWT.
                        After validating the token, the Gateway adds X-User-Id and
                        X-User-Role headers before forwarding the request to this service.
                        """)
                .contact(contact)
                .license(license);

        SecurityScheme bearerSecurityScheme = new SecurityScheme()
                .name(SECURITY_SCHEME_NAME)
                .type(SecurityScheme.Type.HTTP)
                .scheme("bearer")
                .bearerFormat("JWT")
                .description("""
                        Enter the JWT access token received from the login API.

                        Paste only the token value.
                        Do not manually type the word 'Bearer'.
                        Swagger UI adds 'Bearer' automatically.
                        """);

        SecurityRequirement securityRequirement = new SecurityRequirement()
                .addList(SECURITY_SCHEME_NAME);

        Components components = new Components()
                .addSecuritySchemes(
                        SECURITY_SCHEME_NAME,
                        bearerSecurityScheme
                );

        return new OpenAPI()
                .info(apiInfo)
                .servers(List.of(
                        gatewayServer,
                        billServiceServer
                ))
                .components(components)
                .addSecurityItem(securityRequirement);
    }
}
