package com.voltaras.paymentservice.entity;

import com.voltaras.paymentservice.enums.Currency;
import com.voltaras.paymentservice.enums.PaymentMethod;
import com.voltaras.paymentservice.enums.PaymentProvider;
import com.voltaras.paymentservice.enums.PaymentStatus;
import com.voltaras.paymentservice.enums.TransactionType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * A bill payment settled from the VOLTARAS wallet balance.
 *
 * <p>
 * A payment transaction always belongs to a user, an organization and a
 * bill. Only external IDs are stored; no JPA relationship is created to
 * other service databases.
 * </p>
 *
 * <p>
 * Monetary fields use {@link BigDecimal} with scale 2. The payment
 * reference is generated by the service and is immutable. The idempotency
 * key is unique so identical client retries never create duplicates.
 * </p>
 *
 * <p>
 * Bill payments are wallet-funded and therefore complete synchronously as
 * {@link PaymentStatus#SUCCESS}; no card numbers, CVV values, UPI PINs or
 * other sensitive payment data are ever stored.
 * </p>
 */
@Entity
@Table(
        name = "payments",
        uniqueConstraints = {
                @UniqueConstraint(
                        name = "uk_payments_payment_reference",
                        columnNames = "payment_reference"
                ),
                @UniqueConstraint(
                        name = "uk_payments_idempotency_key",
                        columnNames = "idempotency_key"
                )
        },
        indexes = {
                @Index(name = "idx_payments_bill_id", columnList = "bill_id"),
                @Index(name = "idx_payments_organization_id", columnList = "organization_id"),
                @Index(name = "idx_payments_user_id", columnList = "user_id"),
                @Index(name = "idx_payments_status", columnList = "payment_status"),
                @Index(name = "idx_payments_created_at", columnList = "created_at")
        }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentTransaction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Server-generated, immutable payment reference exposed to clients.
     */
    @Column(name = "payment_reference", nullable = false, length = 50)
    private String paymentReference;

    /**
     * Client-supplied idempotency key; unique across all payments.
     */
    @Column(name = "idempotency_key", nullable = false, length = 100)
    private String idempotencyKey;

    /**
     * Kind of transaction. Bill payments are always BILL_PAYMENT.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 20)
    private TransactionType transactionType;

    /**
     * ID of the bill being paid (Bill Service database).
     */
    @Column(name = "bill_id", nullable = false)
    private Long billId;

    /**
     * ID of the organization the payer belongs to (Organization Service).
     */
    @Column(name = "organization_id", nullable = false)
    private Long organizationId;

    /**
     * Auth Service user ID of the payer, received from X-User-Id.
     */
    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal amount;

    @Enumerated(EnumType.STRING)
    @Column(name = "currency", nullable = false, length = 3)
    private Currency currency;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false, length = 20)
    private PaymentMethod paymentMethod;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", nullable = false, length = 20)
    private PaymentStatus status;

    /**
     * Provider used. Bill payments are wallet-funded, so this is null.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "provider", length = 20)
    private PaymentProvider provider;

    /**
     * Provider-side transaction ID, always generated by the provider
     * (never accepted from the client).
     */
    @Column(name = "provider_transaction_id", length = 100)
    private String providerTransactionId;

    @Column(name = "failure_code", length = 50)
    private String failureCode;

    @Column(name = "failure_reason", length = 500)
    private String failureReason;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    @Column(name = "paid_at")
    private LocalDateTime paidAt;

    @PrePersist
    protected void onCreate() {

        LocalDateTime now = LocalDateTime.now();

        createdAt = now;
        updatedAt = now;

        if (transactionType == null) {
            transactionType = TransactionType.BILL_PAYMENT;
        }

        if (status == null) {
            status = PaymentStatus.PENDING;
        }
    }

    @PreUpdate
    protected void onUpdate() {

        updatedAt = LocalDateTime.now();
    }
}
