package com.voltaras.meterreadingservice.util;

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * Tariff estimation used by the daily electricity usage endpoints.
 *
 * <p>The slab rates and charges mirror the bill-service
 * ({@code BillCalculator}) so that the daily and month-to-date cost
 * estimates shown in the consumer portal stay consistent with generated
 * bills:</p>
 *
 * <ul>
 *     <li>0–100 units: ₹1.50 per unit</li>
 *     <li>101–200 units: ₹2.50 per unit</li>
 *     <li>201–300 units: ₹4.00 per unit</li>
 *     <li>Above 300 units: ₹6.00 per unit</li>
 *     <li>Fixed charge: ₹100.00 per month</li>
 *     <li>Tax: 5% of (energy charge + fixed charge)</li>
 * </ul>
 *
 * <p>All amounts are estimates. The authoritative amount for a billing
 * period remains the bill generated by the bill-service.</p>
 */
public final class TariffCalculator {

    /** Monetary scale used by every amount. */
    public static final int MONEY_SCALE = 2;

    /** Blended per-unit rate scale used for the estimate. */
    public static final int RATE_SCALE = 4;

    /** First-slab rate, also the fallback when no consumption exists. */
    public static final BigDecimal RATE_SLAB_ONE = new BigDecimal("1.50");

    private static final BigDecimal RATE_SLAB_TWO = new BigDecimal("2.50");
    private static final BigDecimal RATE_SLAB_THREE = new BigDecimal("4.00");
    private static final BigDecimal RATE_SLAB_FOUR = new BigDecimal("6.00");

    private static final BigDecimal SLAB_ONE_UPPER = new BigDecimal("100");
    private static final BigDecimal SLAB_TWO_UPPER = new BigDecimal("200");
    private static final BigDecimal SLAB_THREE_UPPER = new BigDecimal("300");

    private static final BigDecimal FIXED_CHARGE = new BigDecimal("100.00");
    private static final BigDecimal TAX_RATE = new BigDecimal("0.05");

    private TariffCalculator() {
        // Utility class; instances are not allowed.
    }

    /**
     * Calculates the energy charge for the given units using progressive
     * tariff slabs (identical to the bill-service rule).
     *
     * @param unitsConsumed consumed units (must not be negative)
     * @return energy charge with scale 2
     */
    public static BigDecimal energyCharge(BigDecimal unitsConsumed) {
        requireNonNegative(unitsConsumed, "unitsConsumed");

        BigDecimal charge;

        if (unitsConsumed.compareTo(SLAB_ONE_UPPER) <= 0) {
            charge = unitsConsumed.multiply(RATE_SLAB_ONE);

        } else if (unitsConsumed.compareTo(SLAB_TWO_UPPER) <= 0) {
            charge = SLAB_ONE_UPPER
                    .multiply(RATE_SLAB_ONE)
                    .add(
                            unitsConsumed
                                    .subtract(SLAB_ONE_UPPER)
                                    .multiply(RATE_SLAB_TWO)
                    );

        } else if (unitsConsumed.compareTo(SLAB_THREE_UPPER) <= 0) {
            charge = SLAB_ONE_UPPER
                    .multiply(RATE_SLAB_ONE)
                    .add(SLAB_ONE_UPPER.multiply(RATE_SLAB_TWO))
                    .add(
                            unitsConsumed
                                    .subtract(SLAB_TWO_UPPER)
                                    .multiply(RATE_SLAB_THREE)
                    );

        } else {
            charge = SLAB_ONE_UPPER
                    .multiply(RATE_SLAB_ONE)
                    .add(SLAB_ONE_UPPER.multiply(RATE_SLAB_TWO))
                    .add(SLAB_ONE_UPPER.multiply(RATE_SLAB_THREE))
                    .add(
                            unitsConsumed
                                    .subtract(SLAB_THREE_UPPER)
                                    .multiply(RATE_SLAB_FOUR)
                    );
        }

        return scaleMoney(charge);
    }

    /**
     * Effective blended per-unit rate for a consumption total, i.e. the
     * slab-weighted average rate: {@code energyCharge(units) / units}.
     *
     * <p>When there is no consumption yet, the first-slab rate (₹1.50) is
     * returned so the UI can still display a tariff reference.</p>
     *
     * @param unitsConsumed consumed units
     * @return per-unit rate with scale 4
     */
    public static BigDecimal blendedPerUnitRate(BigDecimal unitsConsumed) {
        if (unitsConsumed == null || unitsConsumed.signum() <= 0) {
            return RATE_SLAB_ONE;
        }

        return energyCharge(unitsConsumed)
                .divide(unitsConsumed, RATE_SCALE, RoundingMode.HALF_UP);
    }

    /**
     * Estimates the month-to-date bill for the given units: energy charge +
     * fixed charge + 5% tax (mirrors the bill-service formula).
     *
     * <p>Returns {@code 0.00} when no units have been consumed.</p>
     *
     * @param unitsConsumed month-to-date consumed units
     * @return estimated month cost with scale 2
     */
    public static BigDecimal estimatedMonthCost(BigDecimal unitsConsumed) {
        if (unitsConsumed == null || unitsConsumed.signum() <= 0) {
            return new BigDecimal("0.00");
        }

        BigDecimal energyCharge = energyCharge(unitsConsumed);
        BigDecimal tax = energyCharge
                .add(FIXED_CHARGE)
                .multiply(TAX_RATE);

        return scaleMoney(
                energyCharge
                        .add(FIXED_CHARGE)
                        .add(tax)
        );
    }

    /**
     * Normalizes a monetary value to scale 2 using
     * {@link RoundingMode#HALF_UP}.
     */
    public static BigDecimal scaleMoney(BigDecimal value) {
        if (value == null) {
            throw new IllegalArgumentException("value must not be null");
        }
        return value.setScale(MONEY_SCALE, RoundingMode.HALF_UP);
    }

    private static void requireNonNegative(BigDecimal value, String name) {
        if (value == null) {
            throw new IllegalArgumentException(name + " must not be null");
        }
        if (value.signum() < 0) {
            throw new IllegalArgumentException(name + " must not be negative");
        }
    }
}
