package com.voltaras.complaintservice.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Configures OpenAPI documentation and Swagger UI for the
 * VOLTARAS Complaint Service.
 *
 * <p>
 * Swagger documentation is generated by complaint-service on port 8087,
 * while API requests are normally executed through the API Gateway on
 * port 8080 with a Bearer JWT.
 * </p>
 */
@Configuration
public class OpenApiConfig {

    private static final String SECURITY_SCHEME_NAME = "bearerAuth";

    @Bean
    public OpenAPI complaintServiceOpenAPI() {

        // Swagger executes protected API requests through API Gateway.
        Server gatewayServer = new Server()
                .url("http://localhost:8080")
                .description("VOLTARAS API Gateway");

        // Direct complaint-service URL is useful only for local debugging;
        // it must not be publicly exposed in production.
        Server complaintServiceServer = new Server()
                .url("http://localhost:8087")
                .description("Complaint Service - Direct Local Access");

        Contact contact = new Contact()
                .name("VOLTARAS Development Team");

        Info apiInfo = new Info()
                .title("VOLTARAS Complaint Service API")
                .version("1.0.0")
                .description("""
                        REST API documentation for the VOLTARAS Complaint Service.

                        Consumers raise complaints (subject, description, category),
                        track their status, edit them while OPEN and add comments.
                        Admins review the full complaint queue, assign complaints,
                        drive the OPEN -> IN_PROGRESS -> RESOLVED -> CLOSED lifecycle
                        and add resolution comments. Every status change produces a
                        status-history record and publishes a
                        ComplaintStatusChangedEvent to the Notification Service
                        through RabbitMQ.

                        Authentication is performed by the API Gateway using JWT.
                        After validating the token, the Gateway adds X-User-Id and
                        X-User-Role headers before forwarding the request to this
                        service; authorization (ADMIN / ownership) is enforced in
                        the service layer. The gateway role claim is issued by the
                        Auth Service as the RoleType name — exactly 'ADMIN' or
                        'CONSUMER'.

                        COMPLAINT LIFECYCLE
                        OPEN -> IN_PROGRESS -> RESOLVED -> CLOSED
                        CLOSED is terminal. Complaints are never cancelled or
                        deleted. Status transitions are validated against the
                        approved transition table.
                        """)
                .contact(contact);

        SecurityScheme bearerSecurityScheme = new SecurityScheme()
                .name(SECURITY_SCHEME_NAME)
                .type(SecurityScheme.Type.HTTP)
                .scheme("bearer")
                .bearerFormat("JWT")
                .description("""
                        Enter the JWT access token received from the login API.

                        Paste only the token value.
                        Do not manually type the word 'Bearer'.
                        Swagger UI adds 'Bearer' automatically.
                        """);

        SecurityRequirement securityRequirement = new SecurityRequirement()
                .addList(SECURITY_SCHEME_NAME);

        Components components = new Components()
                .addSecuritySchemes(SECURITY_SCHEME_NAME, bearerSecurityScheme);

        return new OpenAPI()
                .info(apiInfo)
                .servers(List.of(gatewayServer, complaintServiceServer))
                .components(components)
                .addSecurityItem(securityRequirement);
    }
}
