package com.voltaras.paymentservice.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Configures OpenAPI documentation and Swagger UI for the
 * VOLTARAS Payment Service.
 *
 * <p>
 * Swagger documentation is generated by payment-service on port 8086, while
 * API requests are executed through the API Gateway on port 8080.
 * </p>
 */
@Configuration
public class OpenApiConfig {

    private static final String SECURITY_SCHEME_NAME = "bearerAuth";

    @Bean
    public OpenAPI paymentServiceOpenAPI() {

        // Swagger executes protected API requests through API Gateway.
        Server gatewayServer = new Server()
                .url("http://localhost:8080")
                .description("VOLTARAS API Gateway");

        // Direct payment-service URL is useful only for local debugging.
        Server paymentServiceServer = new Server()
                .url("http://localhost:8086")
                .description("Payment Service - Direct Local Access");

        Contact contact = new Contact()
                .name("VOLTARAS Development Team");

        License license = new License()
                .name("VOLTARAS Project License");

        Info apiInfo = new Info()
                .title("VOLTARAS Payment Service API")
                .version("2.1.0")
                .description("""
                        REST API documentation for the VOLTARAS Payment Service.

                        The service implements the prepaid wallet flow:
                        • Users recharge their VOLTARAS wallet with UPI or CARD
                          through the Razorpay payment gateway in sandbox/test
                          mode (POST /api/recharges/orders).
                        • Razorpay confirms the payment through a
                          signature-protected webhook
                          (POST /api/payments/webhooks/razorpay), which credits
                          the wallet on success.
                        • Bills are paid from the wallet balance
                          (POST /api/bills/{billId}/payments), which debits the
                          wallet and notifies the Bill Service.

                        No card numbers, CVV values, UPI PINs or bank
                        credentials are ever accepted or stored.

                        Authentication is performed by the API Gateway using JWT.
                        After validating the token, the Gateway adds X-User-Id and
                        X-User-Role headers before forwarding the request to this
                        service. The webhook endpoint is the only public API; it is
                        protected by the RAZORPAY_WEBHOOK_SECRET shared secret.

                        AUTH SERVICE VERIFICATION
                        Before recharge order creation, recharge history, wallet
                        balance reads and bill payments, this service verifies the
                        authenticated user with the Auth Service through a Feign
                        client (GET /api/auth/internal/users/{userId}, resolved via
                        Eureka). The Auth Service checks the forwarded Bearer token
                        and returns the user profile (userId, email, fullName, role,
                        active); this service rejects the operation when the user
                        does not exist (404 USER_NOT_FOUND), is deactivated
                        (403 USER_INACTIVE) or the identity does not match the
                        gateway headers (401 UNAUTHORIZED_USER). The auth database
                        is never read directly.

                        PAYMENT STATUSES
                        • CREATED    - recharge order created at the gateway
                        • PENDING    - authorized, awaiting capture
                        • SUCCESS    - completed; wallet credited / bill paid
                        • FAILED     - failed; create a new order to retry
                        • CANCELLED  - cancelled before completion
                        • REFUNDED   - refunded after success (terminal)

                        IDEMPOTENCY
                        Both recharge orders and bill payments require the
                        Idempotency-Key header. Replaying the same key with the
                        same payload returns the original result; reusing it with
                        different data returns 409 IDEMPOTENCY_CONFLICT.

                        MOCK                        TESTING WITHOUT REAL MONEY (RAZORPAY SANDBOX)
                        Razorpay test keys (rzp_test_...) work against the
                        Razorpay sandbox: order creation succeeds and Razorpay
                        lets you simulate captured and failed payments from its
                        dashboard, triggering real webhooks against this service.
                        For fully offline testing, the RazorpayGatewayClient is
                        abstracted and can be mocked in automated tests.
                        """)
                .contact(contact)
                .license(license);

        SecurityScheme bearerSecurityScheme = new SecurityScheme()
                .name(SECURITY_SCHEME_NAME)
                .type(SecurityScheme.Type.HTTP)
                .scheme("bearer")
                .bearerFormat("JWT")
                .description("""
                        Enter the JWT access token received from the login API.

                        Paste only the token value.
                        Do not manually type the word 'Bearer'.
                        Swagger UI adds 'Bearer' automatically.
                        """);

        SecurityRequirement securityRequirement = new SecurityRequirement()
                .addList(SECURITY_SCHEME_NAME);

        Components components = new Components()
                .addSecuritySchemes(
                        SECURITY_SCHEME_NAME,
                        bearerSecurityScheme
                );

        return new OpenAPI()
                .info(apiInfo)
                .servers(List.of(
                        gatewayServer,
                        paymentServiceServer
                ))
                .components(components)
                .addSecurityItem(securityRequirement);
    }
}
