package com.voltaras.organizationservice.config;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.security.SecurityRequirement;
import io.swagger.v3.oas.models.security.SecurityScheme;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * Configures OpenAPI documentation and Swagger UI for the
 * VOLTARAS Organization Service.
 *
 * Swagger documentation is generated by organization-service on port 8085,
 * while API requests are executed through API Gateway on port 8080.
 */
@Configuration
public class OpenApiConfig {

    private static final String SECURITY_SCHEME_NAME = "bearerAuth";

    @Bean
    public OpenAPI organizationServiceOpenAPI() {

        // Swagger executes protected API requests through API Gateway.
        Server gatewayServer = new Server()
                .url("http://localhost:8080")
                .description("VOLTARAS API Gateway");

        // Direct organization-service URL is useful only for local debugging.
        Server organizationServiceServer = new Server()
                .url("http://localhost:8085")
                .description("Organization Service - Direct Local Access");

        Contact contact = new Contact()
                .name("VOLTARAS Development Team");

        License license = new License()
                .name("VOLTARAS Project License");

        Info apiInfo = new Info()
                .title("VOLTARAS Organization Service API")
                .version("1.0.0")
                .description("""
                        REST API documentation for the VOLTARAS Organization Service.

                        This service manages:

                        • Organizations
                        • Organization memberships
                        • Join requests
                        • System-admin organization operations
                        • Buildings
                        • Blocks
                        • Floors
                        • Units

                        Authentication is performed by the API Gateway using JWT.
                        After validating the token, the Gateway adds X-User-Id and
                        X-User-Role headers before forwarding the request to this service.
                        """)
                .contact(contact)
                .license(license);

        SecurityScheme bearerSecurityScheme = new SecurityScheme()
                .name(SECURITY_SCHEME_NAME)
                .type(SecurityScheme.Type.HTTP)
                .scheme("bearer")
                .bearerFormat("JWT")
                .description("""
                        Enter the JWT access token received from the login API.

                        Paste only the token value.
                        Do not manually type the word 'Bearer'.
                        Swagger UI adds 'Bearer' automatically.
                        """);

        SecurityRequirement securityRequirement = new SecurityRequirement()
                .addList(SECURITY_SCHEME_NAME);

        Components components = new Components()
                .addSecuritySchemes(
                        SECURITY_SCHEME_NAME,
                        bearerSecurityScheme
                );

        return new OpenAPI()
                .info(apiInfo)
                .servers(List.of(
                        gatewayServer,
                        organizationServiceServer
                ))
                .components(components)
                .addSecurityItem(securityRequirement);
    }
}