package com.voltaras.notificationservice.enums;

/**
 * Kind of notification.
 *
 * <p>
 * Event-driven notifications are created by the RabbitMQ listeners
 * ({@code BILL_GENERATED}, {@code PAYMENT_SUCCESS},
 * {@code RECHARGE_SUCCESS}, {@code COMPLAINT_STATUS_UPDATED}); the
 * {@link #MANUAL} type is reserved for notifications created by an ADMIN
 * through the REST API.
 * </p>
 */
public enum NotificationType {

    /** A bill was generated by the Bill Service. */
    BILL_GENERATED,

    /** A bill payment completed successfully. */
    PAYMENT_SUCCESS,

    /** A wallet recharge completed successfully. */
    RECHARGE_SUCCESS,

    /** The status of a complaint changed. */
    COMPLAINT_STATUS_UPDATED,

    /** Notification created manually by an ADMIN. */
    MANUAL
}
